# Default values for istio-bookinfo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gateway:
  selector: ingressgateway
  hostname: 
    - 192.168.64.5

  httpsRedirect: false

  tls:
    enabled: false
    secretName: bookinfo-tls
    gatewayNamespace: istio-system
    acme:
      enabled: false
      certManager:
        version: certmanager.k8s.io/v1alpha1
      renewBefore: 720h
      issuerName: letsencrypt
      issuerKind: ClusterIssuer
