---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bookinfo
  namespace: prod
  annotations:
    fluxcd.io/ignore: "true"
    fluxcd.io/automated: "true"
spec:
  releaseName: bookinfo
  chart:
    git: git@github.com:meowveen/gitops-istio
    ref: master
    path: prod/bookinfo/chart
