---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bookinfo
  namespace: prod
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
spec:
  releaseName: bookinfo
  chart:
    git: git@github.com:meowveen/gitops-istio
    ref: master
    path: prod/bookinfo/chart
  values:
    image:
      repository: https://evry-ace.github.io/helm-charts/evry-ace/istio-bookinfo
    service:
      enabled: true
      type: ClusterIP
    ingress:
      enabled: true
      path: /
      hosts:
      - 10.106.68.214.nip.io
